<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Degree Bachelor' => 'Bachelor',
  'Degree Diploma' => 'Diplom',
  'Degree Encoded' => '',
  'Degree Ma' => 'M.A.',
  'Degree Master' => 'Master',
  'Degree Phd' => 'PhD',
  'Degree Postdoc' => 'Postdoc',
  'Degree Student' => 'Student',
  'File could not be found, sorry.' => 'Datei nicht gefunden.',
  'Is Scholarship' => 'Stipendium',
  'Is Thesis' => 'Abschlussarbeit',
  'Is Working Student' => 'Werkstudent',
  'Job Version' => 'Job Version',
  'Publisher Email' => 'E-Mail',
  'Publisher Name' => 'Name',
  'Publisher Phone' => 'Telefon',
  'Jobtype' => '@@Art der Arbeitsstelle@@',
  '{attribute} cannot be blank.' => '@@{attribute} ist ein Pflichtfeld.@@',
  'Attachment' => 'Anhang',
  'Author' => 'Autor',
  'City' => 'Stadt',
  'Company' => 'Unternehmen',
  'Company Homepage' => 'Homepage des Unternehmens',
  'Country' => 'Land',
  'Date Added' => 'Erstellungsdatum',
  'Degree' => 'Abschluss',
  'Description' => 'Beschreibung',
  'Expiration Date' => 'Ablaufdatum',
  'How To Apply' => 'Bewerbungsweg',
  'ID' => 'ID',
  'Is Fulltime' => 'Vollzeit',
  'Is Internship' => 'Praktikum',
  'Is Nation Wide' => 'Bundesweit',
  'Is Parttime' => 'Teilzeit',
  'Is Regular Job' => 'Vollzeit',
  'Is Scientific Position' => 'Wissenschaftliche Position',
  'Is Telecommute' => 'Telearbeit',
  'Is Voluntary Service' => 'Ehrenamt',
  'Is Working Student Position' => 'Internship',
  'Reviewer' => 'Gutachter',
  'Sector' => 'Branche',
  'Source' => 'Quelle',
  'State' => 'Bundesland',
  'Status' => 'Status',
  'Study' => 'Studienrichtungen',
  'Submit' => 'Absenden',
  'Title' => 'Titel',
  'Your request is not valid.' => 'Ungültige Anfrage',
  'Zipcode' => 'Postleitzahl',
  'cancel' => 'Abbrechen',
  'or' => 'oder',
  'Shadow Tags' => 'Versteckte Tags',
);
